swagger: '2.0'
info:
  title: Gamification platform
  description: API specification of th gamify platform
  version: "0.1.0"
# the domain of the service
host: localhost
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /users:
    get:
      summary: get all users
      description: |
        The Users endpoint returns information about the users. The response includes the display username and the email, badges and scale points.
      tags:
        - User
      responses:
        200:
          description: Ok, Array of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/{username}:
    get:
      summary: User Information
      description: |
        The User endpoint returns information about the user, its badges and pointscales.
      parameters:
        - name: username
          in: path
          description: User's username
          required: true
          type: string
      tags:
        - User
      responses:
        200:
          description: Ok, User object
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  

  /badges:
    get:
      summary: All Badges
      description: The Badges endpoint returns information about all the badges.
      tags:
        - Badges
      responses:
        200:
          description: Ok, An array of badges
          schema:
            type: array
            items:
              $ref: '#/definitions/Badge'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a new Badge
      description: Create a new Badge.
      parameters:
        - name: badge
          in: body
          description: Badge to add
          required: true
          schema:
            $ref: '#/definitions/Badge'
      tags:
        - Badge
      responses:
        201:
          description: Created
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /pointScales:
    get:
      summary: All PointScales
      description: The PointScales endpoint returns information about all the pointScales.
      tags:
        - PointScales
      responses:
        200:
          description: An array of PointScales
          schema:
            type: array
            items:
              $ref: '#/definitions/PointScale'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a new PointScale
      description: Create a new PointScale.
      parameters:
        - name: pointScale
          in: body
          description: PointScale to add
          required: true
          schema:
            $ref: '#/definitions/PointScale'
      tags:
        - PointScale
      responses:
        201:
          description: Created
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'


definitions:

  Badge:
    type: object
    properties:
      name:
        type: string
        description: Badge name.
      description:
        type: string
        description: PointScale description
        
  PointScale:
    type: object
    properties:
      name:
        type: string
        description: PointScale name.
      description:
        type: string
        description: PointScale description

  User:
    type: object
    properties:
      username:
        type: string
        description: Username of the user.
      email:
        type: string
        description: Email of the user.
      badges:
        type: array
        items:
          $ref: '#/definitions/Badge'
        description: Badges
     ## pointscales:
  
      

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string